// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/api/grpc/pb/access.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	SongId        string                 `protobuf:"bytes,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessCheckRequest) Reset() {
	*x = AccessCheckRequest{}
	mi := &file_internal_api_grpc_pb_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckRequest) ProtoMessage() {}

func (x *AccessCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_pb_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckRequest.ProtoReflect.Descriptor instead.
func (*AccessCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_pb_access_proto_rawDescGZIP(), []int{0}
}

func (x *AccessCheckRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AccessCheckRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

type AccessCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessCheckResponse) Reset() {
	*x = AccessCheckResponse{}
	mi := &file_internal_api_grpc_pb_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckResponse) ProtoMessage() {}

func (x *AccessCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_pb_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckResponse.ProtoReflect.Descriptor instead.
func (*AccessCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_pb_access_proto_rawDescGZIP(), []int{1}
}

func (x *AccessCheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_internal_api_grpc_pb_access_proto protoreflect.FileDescriptor

const file_internal_api_grpc_pb_access_proto_rawDesc = "" +
	"\n" +
	"!internal/api/grpc/pb/access.proto\x12\acontent\"H\n" +
	"\x12AccessCheckRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\tR\x06songId\"/\n" +
	"\x13AccessCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2L\n" +
	"\x06Access\x12B\n" +
	"\x05Check\x12\x1b.content.AccessCheckRequest\x1a\x1c.content.AccessCheckResponseB/Z-radio/content-service/internal/api/grpc/pb;pbb\x06proto3"

var (
	file_internal_api_grpc_pb_access_proto_rawDescOnce sync.Once
	file_internal_api_grpc_pb_access_proto_rawDescData []byte
)

func file_internal_api_grpc_pb_access_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_pb_access_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_pb_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_pb_access_proto_rawDesc), len(file_internal_api_grpc_pb_access_proto_rawDesc)))
	})
	return file_internal_api_grpc_pb_access_proto_rawDescData
}

var file_internal_api_grpc_pb_access_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_grpc_pb_access_proto_goTypes = []any{
	(*AccessCheckRequest)(nil),  // 0: content.AccessCheckRequest
	(*AccessCheckResponse)(nil), // 1: content.AccessCheckResponse
}
var file_internal_api_grpc_pb_access_proto_depIdxs = []int32{
	0, // 0: content.Access.Check:input_type -> content.AccessCheckRequest
	1, // 1: content.Access.Check:output_type -> content.AccessCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_pb_access_proto_init() }
func file_internal_api_grpc_pb_access_proto_init() {
	if File_internal_api_grpc_pb_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_pb_access_proto_rawDesc), len(file_internal_api_grpc_pb_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_pb_access_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_pb_access_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_pb_access_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_pb_access_proto = out.File
	file_internal_api_grpc_pb_access_proto_goTypes = nil
	file_internal_api_grpc_pb_access_proto_depIdxs = nil
}
