// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/infrastructure/grpc/pb/stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_internal_infrastructure_grpc_pb_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_pb_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_pb_stream_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type AdvanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvanceRequest) Reset() {
	*x = AdvanceRequest{}
	mi := &file_internal_infrastructure_grpc_pb_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceRequest) ProtoMessage() {}

func (x *AdvanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_pb_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceRequest.ProtoReflect.Descriptor instead.
func (*AdvanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_pb_stream_proto_rawDescGZIP(), []int{1}
}

func (x *AdvanceRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StreamStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	CurrentQueueId string                 `protobuf:"bytes,2,opt,name=current_queue_id,json=currentQueueId,proto3" json:"current_queue_id,omitempty"`
	SongId         string                 `protobuf:"bytes,3,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	StartedAt      int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // unix timestamp nanos
	IsActive       bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Revision       int64                  `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamStateResponse) Reset() {
	*x = StreamStateResponse{}
	mi := &file_internal_infrastructure_grpc_pb_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateResponse) ProtoMessage() {}

func (x *StreamStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_pb_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateResponse.ProtoReflect.Descriptor instead.
func (*StreamStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_pb_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamStateResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamStateResponse) GetCurrentQueueId() string {
	if x != nil {
		return x.CurrentQueueId
	}
	return ""
}

func (x *StreamStateResponse) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *StreamStateResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *StreamStateResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StreamStateResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_internal_infrastructure_grpc_pb_stream_proto protoreflect.FileDescriptor

const file_internal_infrastructure_grpc_pb_stream_proto_rawDesc = "" +
	"\n" +
	",internal/infrastructure/grpc/pb/stream.proto\x12\x06stream\".\n" +
	"\x0fGetStateRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"-\n" +
	"\x0eAdvanceRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xcd\x01\n" +
	"\x13StreamStateResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12(\n" +
	"\x10current_queue_id\x18\x02 \x01(\tR\x0ecurrentQueueId\x12\x17\n" +
	"\asong_id\x18\x03 \x01(\tR\x06songId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1a\n" +
	"\brevision\x18\x06 \x01(\x03R\brevision2\x91\x01\n" +
	"\rStreamService\x12@\n" +
	"\bGetState\x12\x17.stream.GetStateRequest\x1a\x1b.stream.StreamStateResponse\x12>\n" +
	"\aAdvance\x12\x16.stream.AdvanceRequest\x1a\x1b.stream.StreamStateResponseB9Z7radio/sender-service/internal/infrastructure/grpc/pb;pbb\x06proto3"

var (
	file_internal_infrastructure_grpc_pb_stream_proto_rawDescOnce sync.Once
	file_internal_infrastructure_grpc_pb_stream_proto_rawDescData []byte
)

func file_internal_infrastructure_grpc_pb_stream_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_grpc_pb_stream_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_grpc_pb_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_grpc_pb_stream_proto_rawDesc), len(file_internal_infrastructure_grpc_pb_stream_proto_rawDesc)))
	})
	return file_internal_infrastructure_grpc_pb_stream_proto_rawDescData
}

var file_internal_infrastructure_grpc_pb_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_infrastructure_grpc_pb_stream_proto_goTypes = []any{
	(*GetStateRequest)(nil),     // 0: stream.GetStateRequest
	(*AdvanceRequest)(nil),      // 1: stream.AdvanceRequest
	(*StreamStateResponse)(nil), // 2: stream.StreamStateResponse
}
var file_internal_infrastructure_grpc_pb_stream_proto_depIdxs = []int32{
	0, // 0: stream.StreamService.GetState:input_type -> stream.GetStateRequest
	1, // 1: stream.StreamService.Advance:input_type -> stream.AdvanceRequest
	2, // 2: stream.StreamService.GetState:output_type -> stream.StreamStateResponse
	2, // 3: stream.StreamService.Advance:output_type -> stream.StreamStateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_grpc_pb_stream_proto_init() }
func file_internal_infrastructure_grpc_pb_stream_proto_init() {
	if File_internal_infrastructure_grpc_pb_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_grpc_pb_stream_proto_rawDesc), len(file_internal_infrastructure_grpc_pb_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_grpc_pb_stream_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_grpc_pb_stream_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_grpc_pb_stream_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_grpc_pb_stream_proto = out.File
	file_internal_infrastructure_grpc_pb_stream_proto_goTypes = nil
	file_internal_infrastructure_grpc_pb_stream_proto_depIdxs = nil
}
