env: dev
log_level: info

http:
  addr: ":8081"
  read_header_timeout: 5s

redis:
  addr: redis:6379
  password: ""
  db: 0

stream_service_grpc: "stream-service:8082"
content_service_url: "http://content-service:8081"

chunk_size: 65536        # 64KB
buffer_seconds: 5
